# Max Maksutova Assignment 1

## Problem Statement: Analyzing Daily Stock Data with Alpha Vantage API

### Overview
In this assignment, you will write a Python script to fetch and analyze daily time series stock data from the Alpha Vantage API for a set of prominent technology stocks (the "Mag 7" tickers). You will then convert the collected data into a pandas DataFrame for further analysis.

### Objectives
- **Data Retrieval:**  
  Use the `requests` library to retrieve daily stock data for the Mag 7 Tickers:

  **Mag 7 Tickers:**

**AAPL**: Apple Inc.
**MSFT**: Microsoft Corporation
**AMZN**: Amazon.com, Inc.
**GOOGL**: Alphabet Inc.
**META**: Meta Platforms, Inc.
**TSLA**: Tesla, Inc.
**NVDA**: Nvidia Corporation

- **API Interaction:**  
  For each stock ticker, construct the appropriate API URL using your Alpha Vantage API key and send an HTTP GET request.  
  Ensure that the API response is successful (HTTP status code 200).

- **Data Extraction:**  
  Extract the "Time Series (Daily)" portion of the JSON response.  
  Since the time series data is provided as a nested dictionary (with dates as keys), iterate over this dictionary.

- **Data Transformation:**  [An example/tutorial with code is provided to do this]
  For each date in the time series data:
  - Create a dictionary that includes the date, the stock ticker, and the day's data (such as open, high, low, close, and volume).
  - Use the dictionary `update` method to merge the date-specific data with the ticker information.
  - Append each resulting dictionary to a list to accumulate all the records.

- **Data Normalization:**  
  Convert the list of dictionaries into a pandas DataFrame.  
  This DataFrame will have columns corresponding to the date, ticker, and the daily stock data, making it easier to analyze the data further.

### Final Deliverable
Your final Python script should include:
- Import statements for `pandas` and `requests`.
- A defined list of stock tickers and your Alpha Vantage API key.
- A loop that iterates over each ticker to:
  - Construct the API URL.
  - Send a request to the API.
  - Process and transform the JSON response.
- Code that converts the accumulated list of dictionaries into a pandas DataFrame. [Provided to you]

By completing this assignment, you will demonstrate your ability to interact with APIs, process nested JSON data, and utilize pandas for data manipulation and analysis.

**get your API key from:** 
[https://www.alphavantage.co/support/#api-key](https://www.alphavantage.co/support/#api-key)

# 1: Import necessary modules

We need to import the `pandas` module for data manipulation and the `requests` module for making HTTP requests.

```python
import pandas as pd
import requests

In [1]:
import pandas as pd
import requests

# 2: Define the list of stocks and API key

We need to define a list of stock symbols that we want to analyze and specify our Alpha Vantage API key.

```python
stocks = ['Ticker1', ... , 'Ticker7'] #Magnificent 7: Alphabet, Amazon, Apple, Meta, Microsoft, Nvidia, Tesla
api_key = 'your_api_key' # Get it from: https://www.alphavantage.co/support/#api-key
    # api kay w/ wm .edu : 8I92ZI5AWDK202T1
    #w/ yr1 : DOMVA9UV2FOKZ2NJ

There is also a minor endpoint that can be used to retrieve a small subset of the publishers we can scan:

Sources /v2/top-headlines/sources â€“ returns information (including name, description, and category) about the most notable sources available for obtaining top headlines from

apiKey
required
Your API key. Alternatively you can provide this via the X-Api-Key HTTP header.

category
Find sources that display news of this category. Possible options: businessentertainmentgeneralhealthsciencesportstechnology. Default: all categories.

language
Find sources that display news in a specific language. Possible opt io ns :  ar de en es fr he it nl no ptrusvudzh. Default: all languages.

country
Find sources that display news in a specific country. Possible  op ti on s:  a ea ra ta ub eb gb rc ac hc nc oc uc zd ee gf rg bg rh kh ui di ei li ni tj pk rl tl vm am xm yn gn ln on zp hp lp tr or sr us as es gs is kt htrtwuausveza. Default: all countries.

Response object
status
string
If the request was successful or not. Options: ok, error. In the case of error a code and message property will be populated.

sources
array[source]
The results of the request.

id
string
The identifier of the news source. You can use this with our other endpoints.

name
string
The name of the news source

description
string
A description of the news source

url
string
The URL of the homepage.

category
string
The type of news to expect from this news source.

language
string
The language that this news source writes in.

country
string
The country this news 

GET https://newsapi.org/v2/top-headlines/sources?category=businessapiKey=API_KEYsource is based in (and primarily writes about).Th

In [2]:
# Mag7 tickers list
stocks = ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'TSLA', 'NVDA']

# My API Key
api_key = '8I92ZI5AWDK202T1'

# new api key
news_api = "8eb5058ccc8845ee8ee3e6fc45609e85"

# Base url for alpha vantage api queries 
base_url = "https://www.alphavantage.co/query?"

# time series tyoe function param
function = 'TIME_SERIES_DAILY'

# 3: Initialize an empty list

We need to initialize an empty list `time_series_data` to store the time series data for each stock.

In [3]:
time_series_data = []  # List to store data for all stocks

# 4: Fetch time series data

We need to loop over each stock symbol, construct the API URL, and make a GET request to that URL. If the response status is OK (200), we need to extract the time series data from the response and append it to `time_series_data`.

### 4.1: Construct the API URL

For each stock symbol, we need to construct the API URL.

### 4.2: Make the API request

We need to make a GET request to the API URL.

response = requests.get(api_url)

### 4.3: Check the response status

Check if the response status is OK (200). If it's not, we print an error message.


if response.status_code == 200:
    ...
else:
    print(f"Error fetching data for {stock}: {response.status_code}")


### 4.4: Extract the time series data

If the response status is OK (200), we need to extract the time series data from the response.

In [4]:
# Loop over stock in stocks to retrieve data from alpha vantage using my api key
for stock in stocks:
    api_url = f'{base_url}function={function}&symbol={stock}&apikey={api_key}' 
    response = requests.get(api_url)
    if response.status_code == 200:
        data = response.json().get('Time Series (Daily)', {})
        for date, values in data.items():
            time_series_data.append({
                "date": date,
                "ticker": stock,
                "1. open": values["1. open"],
                "2. high": values["2. high"],
                "3. low": values["3. low"],
                "4. close": values["4. close"],
                "5. volume": values["5. volume"]
            })
    else:
        print(f"Failed to retrieve data for {stock}.")

# Convert the list into a pandas DataFrame
df = pd.DataFrame(time_series_data)

### Final DF

In [5]:
# Remove numbers and periods from column names and convert to lowercase
df.columns = df.columns.str.replace('[0-9.]', '', regex=True).str.strip().str.lower()

# Convert 'date' column to datetime type
df['date'] = pd.to_datetime(df['date'])

df

          date ticker      open      high       low     close     volume
0   2025-04-16   AAPL  198.3600  200.7000  192.3700  194.2700   59732423
1   2025-04-15   AAPL  201.8550  203.5100  199.8000  202.1400   51343872
2   2025-04-14   AAPL  211.4400  212.9400  201.1621  202.5200  101352911
3   2025-04-11   AAPL  186.1000  199.5400  186.0600  198.1500   87435915
4   2025-04-10   AAPL  189.0650  194.7799  183.0000  190.4200  121879981
..         ...    ...       ...       ...       ...       ...        ...
695 2024-11-26   NVDA  137.7000  139.3000  135.6700  136.9200  190287654
696 2024-11-25   NVDA  141.9900  142.0500  135.8200  136.0200  344941875
697 2024-11-22   NVDA  145.9300  147.1600  141.1000  141.9500  236406154
698 2024-11-21   NVDA  149.3500  152.8900  140.7000  146.6700  400946570
699 2024-11-20   NVDA  147.4100  147.5600  142.7300  145.8900  309871654

[700 rows x 7 columns]

In [6]:
df.to_csv('output.csv', index=False)